packaging_format = 2

id = "petitesannonces"
name = "Petites Annonces"
description.en = "Make your own classified advertising website easily"
description.fr = "Créer simplement et rapidement votre site de Petites Annonces"

version = "0.1.0~ynh3"

maintainers = ["Ccile155"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://github.com/Ccile155/petitesannonces_Fabritech"
code = "https://github.com/Ccile155/petitesannonces_Fabritech"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/annonces"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Ccile155/petitesannonces_Fabritech.git"
        sha256 = "5ca4e4f24b00b0b30645be3db2d433057220dfcf"
        autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php7.4-fpm, php7.4-mysql"

    [resources.database]
    type = "mysql"
